package com.jcdecaux.datacorp.spark.transformation

import com.jcdecaux.datacorp.spark.annotation.{Delivery, InterfaceStability}

import scala.reflect.runtime

/**
  * DeliverySetterMetadata contains information of the @Delivery annotated method, including the name,
  * argument types, the producer and optional
  *
  * @param factoryUUID UUID of factory
  * @param name        name of the method
  * @param argTypes    type of each argument
  * @param producer    the producer class for the given data
  * @param optional    true if optional
  */
@InterfaceStability.Evolving
private[spark] case class FactoryDeliveryMetadata(factoryUUID: String,
                                                  name: String,
                                                  argTypes: List[runtime.universe.Type],
                                                  producer: Class[_ <: Factory[_]],
                                                  optional: Boolean) {

  /**
    * As a setter method may have multiple arguments (even though it's rare), this method will return a list of
    * [[FactoryInput]] for each of argument of setter method
    *
    * @return
    */
  def getFactoryInputs: List[FactoryInput] = argTypes.map(tp => FactoryInput(tp, producer))

}

private[spark] object FactoryDeliveryMetadata {

  /**
    * Build a DeliverySetterMetadata from a given class
    */
  class Builder extends com.jcdecaux.datacorp.spark.Builder[Iterable[FactoryDeliveryMetadata]] {

    var cls: Class[_ <: Factory[_]] = _
    var factoryUUID: String = _
    var metadata: Iterable[FactoryDeliveryMetadata] = _

    def setFactory(factory: Factory[_]): this.type = {
      this.cls = factory.getClass
      this.factoryUUID = factory.getUUID
      this
    }

    override def build(): this.type = {

      log.debug(s"Fetch methods of ${cls.getCanonicalName} having Delivery annotation")

      // Black magic XD
      val classSymbol = runtime.universe.runtimeMirror(getClass.getClassLoader).classSymbol(cls)
      val methodsWithDeliveryAnnotation = classSymbol.info.decls.filter({
        x => x.annotations.exists(y => y.tree.tpe =:= runtime.universe.typeOf[Delivery])
      })

      if (methodsWithDeliveryAnnotation.isEmpty) log.info("No method having @Delivery annotation")

      metadata = methodsWithDeliveryAnnotation.map({
        mth =>

          if (mth.isMethod) {
            log.debug(s"Find @Delivery annotated method ${cls.getCanonicalName}.${mth.name}")

            val annotation = cls
              .getDeclaredMethods
              .find(_.getName == mth.name.toString).get
              .getAnnotation(classOf[Delivery])

            val producerMethod = annotation.annotationType().getDeclaredMethod("producer")
            val optionalMethod = annotation.annotationType().getDeclaredMethod("optional")

            FactoryDeliveryMetadata(
              factoryUUID = factoryUUID,
              name = mth.name.toString,
              argTypes = mth.typeSignature.paramLists.head.map(_.typeSignature),
              producer = producerMethod.invoke(annotation).asInstanceOf[Class[_ <: Factory[_]]],
              optional = optionalMethod.invoke(annotation).asInstanceOf[Boolean]
            )
          } else {
            log.debug(s"Find @Delivery annotated variable ${cls.getCanonicalName}.${mth.name}")

            val annotation = cls
              .getDeclaredField(mth.name.toString.trim)
              .getAnnotation(classOf[Delivery])

            val producerMethod = annotation.annotationType().getDeclaredMethod("producer")
            val optionalMethod = annotation.annotationType().getDeclaredMethod("optional")

            /*
             * If an annotated value was found, then return the default setter created by compiler, which is {valueName}_$eq.
             */
            FactoryDeliveryMetadata(
              factoryUUID = factoryUUID,
              name = mth.name.toString.trim + "_$eq",
              argTypes = List(mth.typeSignature),
              producer = producerMethod.invoke(annotation).asInstanceOf[Class[_ <: Factory[_]]],
              optional = optionalMethod.invoke(annotation).asInstanceOf[Boolean]
            )
          }

      })

      this
    }

    override def get(): Iterable[FactoryDeliveryMetadata] = metadata
  }


  /**
    * DeliverySetterMetadata Builder will create a [[com.jcdecaux.datacorp.spark.transformation.FactoryDeliveryMetadata]]
    * for each setter method (user defined or auto-generated by compiler)
    */
  def builder(): Builder = new Builder()
}